version: "3.9"  # optional but recommended

services:
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: streamlit-app
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
